### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by illtellyoulater** [plribeiro3000/jazz_fingers#10]
Doesn't work anymore in Windows and Ruby 2.2. due to issues with coolline https://github.com/Mon-Ouie/coolline/issues/19

**Comment by aried3r** [comment]
Even with `config.coolline = false`?

**Comment by illtellyoulater** [comment]
Hi @aried3r, pry binary crashes on start and I don't know where to put config.coolline = start

**Comment by plribeiro3000** [comment]
@jjgh Did you try the recommendation in the [README](https://github.com/plribeiro3000/jazz_fingers#options)?

**Comment by plribeiro3000** [comment]
Closing due lack of feedback.

If the error persists or someone is willing to take a stab just comment over here please.
