### ISSUE TITLE
Jumping at the beginning or end of line with CTRL or ALT + arrows

### ISSUE THREAD

**Issue by jerefrer** [plribeiro3000/jazz_fingers#11]
Hi there,

Thank you for building on top of jazz_hands for a more to-date bundle of useful gems.

But there's one thing I lost in the transition : I can't jump to the beginning of words with CTRL or ALT + the arrow keys. I'm very used to navigate like this so it feels very annoying to me not to be able to use them ...

When I try to do for example CTRL + LEFT ARROW and then CTRL + RIGH ARROW I get `5D` and `5C` printed out but the cursor doesn't move, like this:

```
SomeClass5D5C
```

The thing is I don't know why it's not working anymore. Maybe you know ?

**Comment by plribeiro3000** [comment]
So `jazz_fingers` neither `jazz_hands` have anything related to this configuration.
If something stopped adding this feature it must be one of the dependencies. In the bump of the dependencies this feature might have changed or removed.

**Comment by plribeiro3000** [comment]
I could not find anything on the dependency projects that could be the culprit for such behaviour.
Can you confirm this works in `jazz_hands` using the same machine as you are using `jazz_fingers`?

**Comment by jerefrer** [comment]
I confirm it works well on `jazz_hands` on the same machine, same project.

By looking at the Gemfile.lock diff I think the main difference is that `jazz_fingers` is using `byebug` where `jazz_hands` uses `debugger`.

So I've looked at `byebug` directly and found this issue https://github.com/deivid-rodriguez/byebug/issues/118. It seems it's really a byebug issue so I'll stop bothering you here ;)

Thanks for you time !

**Comment by plribeiro3000** [comment]
Wow. Sorry if i missed that issue. =s
So it seems we need to check `readline` to fix that, huh?

**Comment by jerefrer** [comment]
I think it's related to some environments, and to the way you compile ruby. In my case I'm on Archlinux and using RVM.
I haven't managed to find the right trick for now but I'l keep trying.

**Comment by plribeiro3000** [comment]
Hmm. Thank you for the feedback.
Let me know how it goes.

Thanks!

**Comment by jerefrer** [comment]
Okay so actually I just needed to update `jazz_fingers` to update `byebug` and the issue is gone.

But now I've lost colors ... It's not my day ...

I've tried to go at full throttle but still no colors and noawesome print. Hirb works.

```
if defined?(JazzFingers)
  Pry.color = true
  Hirb.enable
  JazzFingers.configure do |config|
    config.colored_prompt = true
    config.awesome_print = true
    config.coolline = true
  end

  require 'jazz_fingers/setup'
end
```

**Comment by plribeiro3000** [comment]
Hmmm, which version of the dependencies are you using?

**Comment by jerefrer** [comment]
```
jazz_fingers (2.0.2)
awesome_print (1.6.1)
coolline (0.5.0)
unicode_utils (1.4.0)
pry (0.10.1)
pry-byebug (3.2.0)
pry-coolline (0.2.5)
pry-doc (0.8.0)
pry-git (0.2.3)
pry-remote (0.1.8)
hirb (0.7.3)
coderay (1.1.0)
method_source (0.8.2)
slop (3.6.0)
```

**Comment by jerefrer** [comment]
Well actually it's not working ... I got misled because before the upgrade `rails c` used to start the console through Pry and now it appears it doesn't. But if I add a `binding.pry` breakpoint then it properly opens Pry with colors and everything **along with the readline bug** ...

**Comment by plribeiro3000** [comment]
Oh yeah. i did remove `pry-rails` as dependency so this code works pretty well in non rails apps.
Maybe we should have this in README?

**Comment by jerefrer** [comment]
Yep definitely
