### ISSUE TITLE
NoMethodError: undefined method `configure' for JazzFingers:Module

### ISSUE THREAD

**Issue by KurtPreston** [plribeiro3000/jazz_fingers#14]
I've included jazz_fingers in the development and test environments.  I'm trying to copy the initializer shown in the README, however, I'm getting the error:

```
NoMethodError: undefined method `configure' for JazzFingers:Module
```

I get the same error if I try to run `JazzFingers.configure` manually in the Rails console.

**Comment by plribeiro3000** [comment]
Which version are you using?

**Comment by KurtPreston** [comment]
Ah, apparently I was running a really old version (0.5.4).  Good call.  Thanks!

**Comment by plribeiro3000** [comment]
:+1:
