### ISSUE TITLE
Deprecated setting prompt via an array of two procs

### ISSUE THREAD

**Issue by aried3r** [plribeiro3000/jazz_fingers#22]
https://github.com/pry/pry/blob/master/CHANGELOG.md#deprecations
https://www.rubydoc.info/gems/pry/Pry/Prompt

I believe that's what's happening here:
https://github.com/plribeiro3000/jazz_fingers/blob/a89eb47055e861ca864c3d87baa7ad4618224999/lib/jazz_fingers.rb#L49
https://github.com/plribeiro3000/jazz_fingers/blob/a89eb47055e861ca864c3d87baa7ad4618224999/lib/jazz_fingers.rb#L24-L32
https://github.com/plribeiro3000/jazz_fingers/blob/a89eb47055e861ca864c3d87baa7ad4618224999/lib/jazz_fingers/prompt.rb#L71-L73

**Comment by plribeiro3000** [comment]
@aried3r Would you be able to open a PR?

**Comment by h35514n** [comment]
@plribeiro3000 PR #23 addresses this issue — let me know what you think
