### ISSUE TITLE
Rails 6.1 deprecation warning: module_parent_name

### ISSUE THREAD

**Issue by h35514n** [plribeiro3000/jazz_fingers#24]
```
DEPRECATION WARNING: `Module#parent_name` has been renamed to `module_parent_name`. 
`parent_name` is deprecated and will be removed in Rails 6.1. 
(called from <main> at config/initializers/jazz_fingers.rb:3)
```

From:

https://github.com/plribeiro3000/jazz_fingers/blob/199555b30a0aa335207b90bd1ceaa84ac492a014/lib/jazz_fingers/configuration.rb#L41-L46

I'll work on a patch this weekend unless someone else takes it

**Comment by plribeiro3000** [comment]
@jmromer Just pushed version `5.2.1`.

Thanks!
