### ISSUE TITLE
Version 5.2.1 shows `jazz_fingers` as application name

### ISSUE THREAD

**Issue by aried3r** [plribeiro3000/jazz_fingers#25]
Version 5.2.0:

```Console
$ rails console
2.7.1 (my_app_name)[1] »
```

Version 5.2.1:

```Console
$ rails console
2.7.1 (jazz_fingers)[1] »
```

**Comment by plribeiro3000** [comment]
Which version of Rails are you using?

**Comment by aried3r** [comment]
Sorry, forgot to mention in the issue. I'm using Rails 6.0.3.2.

**Comment by aried3r** [comment]
Ah, I can see it now. https://github.com/plribeiro3000/jazz_fingers/commit/57c97fa206e3e5eca0397ac844cd6e9487002f3b tries to fix a deprecation warning, but removed the `return` statement. Now `jazz_fingers` is always returned.

Should we return a default like this instead of maybe throwing an exception or displaying a warning? In which cases would this not return a value?

**Comment by plribeiro3000** [comment]
Ouch. Good catch.

Could you open a PR?

**Comment by plribeiro3000** [comment]
I guess just adding return would be enough.

If we can get the application name let use it otherwise use the default which is the gem name.
