### ISSUE TITLE
Replace awesome_print with amazing_print

### ISSUE THREAD

**Issue by h35514n** [plribeiro3000/jazz_fingers#27]
With Ruby 2.7.1, `awesome_print` emits a [deprecation warning](https://github.com/awesome-print/awesome_print/issues/382) when evaluating the Pry prompt:

```
2.7.1 (jazz_fingers)[5] » Array([3])
~/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/formatters/base_formatter.rb:113: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
~/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:63: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
```

It looks like `awesome_print` is abandoned but [there's a maintained fork](https://github.com/awesome-print/awesome_print/issues/382#issuecomment-653524820) it can be replaced with: https://github.com/amazing-print/amazing_print

**Comment by plribeiro3000** [comment]
released as `6.0.0.pre.rc1`

Thanks @jmromer !
