### ISSUE TITLE
Pry-byebug 2.0 is not compatible with pry-remote

### ISSUE THREAD

**Issue by agentGreg** [plribeiro3000/jazz_fingers#3]
After updating to jazz_fingers, I got the following error while trying to work with pry-remote:

``` ruby
[pry-remote] Waiting for client on druby://127.0.0.1:9876
[pry-remote] Client received, starting remote session

From: /home/greg/.rvm/gems/ruby-2.2.0@ibarn/gems/pry-remote-0.1.8/lib/pry-remote.rb @ line 191 PryRemote::Server#teardown:

    182: def teardown
    183:   # Reset output streams
    184:   $stdout = @old_stdout
    185:   $stderr = @old_stderr
    186: 
    187:   # Reset config
    188:   Pry.config.pager = @old_pager
    189: 
    190:   # Reset sysem
 => 191:   Pry.config.system = @old_system
    192: 
    193:   puts "[pry-remote] Remote session terminated"
    194: 
    195:   begin
    196:     @client.kill
    197:   rescue DRb::DRbConnError
    198:     puts "[pry-remote] Continuing to stop service"
    199:   ensure
    200:     puts "[pry-remote] Ensure stop service"
    201:     DRb.stop_service
    202:   end
    203: end
```

From what I have found, this is the issue of the lack of compatibility between pry-byebug 2.0 and pry-remote - see issue deivid-rodriguez/pry-byebug#33 and Mon-Ouie/pry-remote#58.

Pry-remote works fine with pry-byebug 1.3.3, so maybe for now (until the author of pry-byebug solves the issue) the dependency can be weakend?

**Comment by plribeiro3000** [comment]
Ok @matfiz . I'm following both repos now to get updated on that.
Your proposal seems reasonable since `pry-byebug 2.0.0` changelog says:
- Improvements:
  - Compatibility with byebug 3
  - Now pry starts at the first line after binding.pry, not at binding.pry
- Bugfixes:
  - 'continue' doesn't finish pry instance (issue #13)

**Comment by plribeiro3000** [comment]
@matfiz Can you try version `1.0.0`?

Thanks!

**Comment by agentGreg** [comment]
I confirm that with pry-byebut 1.3.3 it works fine :smiley: 

Thanks for the prompt response to this issue :+1:
