### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by MichaelSp** [plribeiro3000/jazz_fingers#4]
Have you tried running this on windows?
After eating one of my cores for almost 1 Minute
I get this error: https://gist.github.com/MichaelSp/905ca6033d9d2398e4d3

**Comment by plribeiro3000** [comment]
@MichaelSp Thank you for submitting this. I will take a look once i get a windows vm running.

**Comment by MichaelSp** [comment]
I had some troubles installing ruby. This could help you to get it started: https://chocolatey.org/

```
choco install ruby2
choco install ruby2.devkit 
```

**Comment by plribeiro3000** [comment]
@MichaelSp I did not manage to get a windows vm yet. Perhaps you could take a deeper look at it?

**Comment by MichaelSp** [comment]
Ok, I managed to track this down to coolline. So I'll file a bug upstream: https://github.com/Mon-Ouie/coolline/issues/19

**Comment by plribeiro3000** [comment]
@MichaelSp Thank you for the feedback. Let me know if i can help anyway.
