### ISSUE TITLE
Disable awesome print

### ISSUE THREAD

**Issue by derrickmar** [plribeiro3000/jazz_fingers#6]
Is it possible to disable awesome print in the console? With Hirb we can do `Hirb.disable` but I don't think they're an equivalent here.

**Comment by plribeiro3000** [comment]
Hey @derrickmar . I´m going to give this a look.

**Comment by skull-squadron** [comment]
Add this to {{project}}/.pryrc or ~/.pryrc

``` ruby
Pry.print = Pry::DEFAULT_PRINT
```

**Comment by skull-squadron** [comment]
Or, I've [refactored](https://github.com/steakknife/jazz_fingers) this gem to allow live feature toggling, like:

``` ruby
JazzFingers.awesome_print = false
JazzFingers.hirb = true
```

Plus, it fixes annoying rough edges with `hirb-unicode` + `less (the *nix command)`.

**Comment by plribeiro3000** [comment]
Hey @steakknife . Could you open a PR with those changes?

I would love to bring them to the next version.

**Comment by skull-squadron** [comment]
Can't right now, but feel free to steal code: https://github.com/plribeiro3000/jazz_fingers/compare/master...steakknife:master

—

**Comment by plribeiro3000** [comment]
@steakknife Sure. i will try to do it later today. Thank you for all your work. :+1:

**Comment by derrickmar** [comment]
Awesome thanks @steakknife. I'm interested in the changes you made and will see them tomorrow!

**Comment by plribeiro3000** [comment]
Hey @steakknife . I just realized you did more changes on your fork.

Would you like to bring them in? I just made a PR to remove mandatory dependency on rails/railties/active_support so the usage of the gem does not look so odd on non rails applications.

LMK your thoughts on it.

**Comment by plribeiro3000** [comment]
Hey @derrickmar. With the latest changes here you can just set `JazzFingers.awesome_print = false` in an initializer and it should take care of deactivate it. =)

As soon as i finish some other changes i will make a new release.
