### ISSUE TITLE
Problem with rails 4.2.x

### ISSUE THREAD

**Issue by simo2409** [plribeiro3000/jazz_fingers#8]
Hi,
I would like to use jazz_fingers in a rails 4.2.x app but on `bundle install` I'm getting a dependency problem:

```
Bundler could not find compatible versions for gem "byebug":
  In Gemfile:
    jazz_fingers (>= 0) ruby depends on
      pry-byebug (~> 1.3) ruby depends on
        byebug (~> 2.2) ruby

    byebug (5.0.0)
```

**Comment by plribeiro3000** [comment]
@simo2409 Sorry for the delay. I will try to fix this when i got so free time to spare.

Would you be able to submit a PR?

**Comment by simo2409** [comment]
I doubt, I tried to fix dependencies but without luck, maybe it's related to pry-byebug gem? I'm not sure

**Comment by plribeiro3000** [comment]
Hmmm, so in master the dependency is different. https://github.com/plribeiro3000/jazz_fingers/blob/master/jazz_fingers.gemspec#L26

Which version of `jazz_fingers` are you using?

**Comment by simo2409** [comment]
None explicit, I just added
`gem 'jazz_fingers'`
to my Gemfile without specifying version

**Comment by simo2409** [comment]
I tried:

```
gem 'jazz_fingers', git: 'git@github.com:plribeiro3000/jazz_fingers.git'
```

and now I get:

```
Fetching gem metadata from https://rubygems.org/..........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "byebug":
  In snapshot (Gemfile.lock):
    byebug (5.0.0)

  In Gemfile:
    jazz_fingers (>= 0) ruby depends on
      pry-byebug (~> 3.1) ruby depends on
        byebug (~> 4.0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by plribeiro3000** [comment]
Did you try `bundle update`?

Some other gem in your Gemfile depend on `byebug ~> 4.0` while `jazz_fingers` depend on version `3.1`.

Which gem you are using that depend on `byebug`?

**Comment by simo2409** [comment]
`bundle update`solved the problem, thank you very much

**Comment by plribeiro3000** [comment]
Sure. You are welcome!
